### ISSUE TITLE
[BUGCHECK] "Depth" capture cannot be performed.

### ISSUE THREAD

**Issue by L020304** [cot6/reshade-addons#1]
How to set the screenshot function to capture depth image? Which effect needs to be enabled?

**Comment by cot6** [comment]
> How to set the screenshot function to capture depth image? Which effect needs to be enabled?

Users are not required to do anything, but this is the bug check, so an unexpected error has caused somewhere.

Open the `ReShade.log` file and find all lines containing `[Screenshot]` and paste them here.
If these lines contain private information (e.g. user name or other), mask part of them.
```
C:\Users\cot6\Desktop
↓
C:\Users\********\Desktop
```

If no errors are logged, try using the experimental version from the following and reproduce the bug check.
https://ci.appveyor.com/project/cot6/reshade-addons/builds/49314638/artifacts
for 64-bit: `ReShade64-Screenshot-By-seri14.zip`

**Comment by L020304** [comment]
I tried using the experimental version, but there were no error records in the ReShade.log file.

Will the screenshot capture feature for normal images be added?

**Comment by cot6** [comment]
> I tried using the experimental version, but there were no error records in the ReShade.log file.

That is odd. Maybe the add-on controlled effect has not compiled.
Currently I have no idea where the program make reach the state to cause bug check.

The effect file is located here.
`%ALLUSERSPROFILE%\ReShade Addons\Seri\reshade-shaders\Shaders\__Addon_ScreenshotDepth_Seri14.addonfx`

> Will the screenshot capture feature for normal images be added?

No, but you can modify the add-on controlled effect.

Copy the file `%ALLUSERSPROFILE%\ReShade Addons\Seri\reshade-shaders\Shaders\__Addon_ScreenshotDepth_Seri14.addonfx` to `%ALLUSERSPROFILE%\ReShade Addons\Seri\reshade-shaders\Shaders\__Addon_ScreenshotDepth_Seri14.addonfxgen` and edit it.

Then the depth image will be saved as you modified it. (Require to restart the application)

**Comment by kjerk** [comment]
@cot6 
~~I'm having this same problem, I thought it was something wrong with my setup until I finally tried A/B testing [v10.6.1](https://github.com/cot6/reshade-addons/releases/tag/v10.6.1) and [10.5.1](https://github.com/cot6/reshade-addons/releases/tag/v10.5.1).~~

So I was in the middle of writing out my settings when I think I stumbled on the problem here. Depth screenshots were not working for me sometimes in some games, and were working in others. Sometime switching versions helped, it seemed random.

Finally I noticed this setting that had been populated automatically, and once I saw it, removing this extra search path broke the depth screenshots, and re-adding it manually fixed them (naturally).
![image](https://github.com/cot6/reshade-addons/assets/2738686/9e476418-8a4b-471e-8a0f-d994c6547d11)

It looks like this setting and file are supposed to populate automatically, but I think this means is that the placement of the `__Addon_ScreenshotDepth_Seri14.addonfx` file as well as being able to find that file (auto adding the search path) is very fickle, and it doesn't work pretty often. And when it doesn't resolve, you can still take screenshots normally but the Depth image doesn't appear, silently failing with no warning, no logs or messages in Reshade.log that I can see.

I think @L020304 could try simply locating `__Addon_ScreenshotDepth_Seri14.addonfx` on their system and add that effect search path in their config to see if that was the issue, but for a larger fix, making the install process, or error messages more robust, or at least adding a note in the Readme about making sure that file can be found would help.

**Comment by kjerk** [comment]
Thanks for the addon by the way, I have been looking for this exact "Screenshot + Depth Buffer" functionality for so long in a combined package, I love it.

**Comment by cot6** [comment]
The behavior of the Screenshot add-on has been changed to solve this issue.
See: https://github.com/cot6/reshade-addons/commit/b808136a714eff02f93e8df06d3850e8af65d805
Please get the binary from the following URL.
https://ci.appveyor.com/project/cot6/reshade-addons/builds/49499492/artifacts

**Comment by cot6** [comment]
The initial process that modifies the ReShade configuration file is still not correctly (Timing issue) because API not supported the some features.
I will make some suggestions for the next ReShade release.
So this issue will not be fixed immediately, but the depth capture feature will work if you manually set the Effect Search Paths, so please do that for now.

**Comment by cot6** [comment]
A useful option in this case is Turn On Effects.
### Ignore
This feature does nothing. This is the default option.
### While myset is active
Turn on effects state if it is disabled when taking screenshot.
When myset is deactivated, this feature will turn off the effects state if the state was switched to enabled.
### When activate myset
Turn on effects state if it is disabled when activating myset.
When myset is deactivated, this feature will turn off the effects state if the state was switched to enabled.

![turn_on_effects_when_activate_myset](https://github.com/cot6/reshade-addons/assets/129574781/a7eaca1b-97ab-4e0d-b0a0-c6c05f858f41)

**Comment by L020304** [comment]
> I think @L020304 could try simply locating `__Addon_ScreenshotDepth_Seri14.addonfx` on their system and add that effect search path in their config to see if that was the issue, but for a larger fix, making the install process, or error messages more robust, or at least adding a note in the Readme about making sure that file can be found would help.

Thank you, （"Depth" capture cannot be performed） does not appear again.
But the tiff file is completely white. Screenshot  not running correctly.

**Comment by cot6** [comment]
If you have succeeded to create the TIFF file, the depth map should be captured. (If you can see the shadow in DisplayDepth effect on scene.)
Note the picture you can see on TIFF is not the same as with ReShade. The depth buffer data needs to be adjusted for the formula of the effects, but the saving data is not required.

Use a viewer or editor that has the ability to handle floating point color.
If the software can handle only 8-bit depth integer color, it may look like filled image.

![screenshot_addon_ss](https://github.com/cot6/reshade-addons/assets/129574781/a826c179-16af-4ada-b371-d4706b1e2259)
![screenshot_addon_gimp_depth](https://github.com/cot6/reshade-addons/assets/129574781/f3362ac4-df20-488f-8a64-24b7fa9f6941)
![screenshot_addon_gimp_color](https://github.com/cot6/reshade-addons/assets/129574781/6f3035fe-c46a-48ed-8cab-1772d196e226)

**Comment by kjerk** [comment]
That's right, the scaling for the depth buffer is very high. I worked on a script to reprocess the depth maps to be more like what DisplayDepth outputs.

Screen
![ex_Screenshot_2024-03-09_00-21-38_0_S](https://github.com/cot6/reshade-addons/assets/2738686/0b5e6408-5cfa-449d-b7e4-b16657f53279)
Depth before
![ex_before_Screenshot_2024-03-09_00-21-38_0_Z](https://github.com/cot6/reshade-addons/assets/2738686/7bf2851f-99bf-425d-83c0-8d72eaa90eb8)
Depth after
![ex_after_Screenshot_2024-03-09_00-21-38_0_Z](https://github.com/cot6/reshade-addons/assets/2738686/cd4e8a2f-fc53-482c-9d84-e1a6d2738b45)

### rescale_tiff_depth.py
```python
import argparse

from PIL import Image
import numpy as np

def parse_args():
    parser = argparse.ArgumentParser(description="Process a depth map stored in a TIFF file.")
    parser.add_argument("--input-path", "--i", type=str, required=True, help="The path to the input depth map TIFF file.")
    parser.add_argument("--output-path", "--o", type=str, required=False, default='', help="The path to save the processed depth map PNG file.")
    parser.add_argument("--no-invert", action="store_true", help="Do not invert the depth map.")
    parser.add_argument("--far-plane", type=float, default=1000.0, help="The far plane distance for the depth map.")
    
    return parser.parse_args()

def main(cmd_args: argparse.Namespace):
    
    input_path = cmd_args.input_path
    far_plane = 1000.0
    skip_invert = cmd_args.no_invert
    
    if cmd_args.output_path:
        output_path = cmd_args.output_path
    else:
        output_path = input_path.replace(".tiff", ".png")
    
    depth_map = Image.open(input_path)
    depth_array = np.array(depth_map)
    
    # Linearize
    linearized_depth = 1.0 / (1.0 - depth_array / far_plane)
    
    # Normalize
    normalized_depth = (linearized_depth - np.min(linearized_depth)) / (np.max(linearized_depth) - np.min(linearized_depth))
    
    # Invert
    if not skip_invert:
        normalized_depth = 1.0 - normalized_depth
    
    # Convert back to an image
    processed_depth_map = Image.fromarray((normalized_depth * 255).astype(np.uint8))
    
    processed_depth_map.save(output_path, compression=3)
    
    print(f"Saved processed depth map to: {output_path}")

if __name__ == '__main__':
    cmd_args = parse_args()
    main(cmd_args)
```

```text
usage: rescale_tiff_depth.py [-h] --input-path INPUT_PATH [--output-path OUTPUT_PATH] [--no-invert]
                                   [--far-plane FAR_PLANE]

Process a depth map stored in a TIFF file.

options:
  -h, --help            show this help message and exit
  --input-path INPUT_PATH, --i INPUT_PATH
                        The path to the input depth map TIFF file.
  --output-path OUTPUT_PATH, --o OUTPUT_PATH
                        The path to save the processed depth map PNG file.
  --no-invert           Do not invert the depth map.
  --far-plane FAR_PLANE
                        The far plane distance for the depth map.
```

Used like (process in place and save to new .png, warning will overwrite if one exists already)
`python rescale_tiff_depth.py -i path/to/image.tiff`
or output to a new file
`python rescale_tiff_depth.py -i "path/to/image.tiff" -o "path/to/output.png" --no-invert`

**Comment by cot6** [comment]
Fixed.
Get updates from the following links.

#### ReShade
Binaries (**Unofficial build**): https://ci.appveyor.com/project/cot6/reshade/builds/49564258/artifacts
Commit: https://github.com/crosire/reshade/commit/358f45439edfbebd2fc91b4c135c762d16f7ad56

#### Add-ons (Preview)
Binaries: https://ci.appveyor.com/project/cot6/reshade-addons/builds/49564757/artifacts
Commit: https://github.com/cot6/reshade-addons/commit/18b11caa87e40c7dcb75a9067829a226c6076a12
