### ISSUE TITLE
having issues setting up depth buffer

### ISSUE THREAD

**Issue by darthmalak1986** [cot6/reshade-addons#2]
Hello im using FSR in quality mode over Horizon Forbidden West and im usin cot6 shaders and i was able to go from a square window that was showing over the depth buffer to this, but still is not being set up correctly

How can i set this up correctly, in the screenshot i have scale over 1.5 and 1.5

I was able to fix over Preview depth buffer witch is fixing my entire screen and i saved the settings using cot6 addon but i dont kow how to set the buffer right without no issues and that weirds lines on the left i dont know what they are 
![Captura de pantalla (1040)](https://github.com/cot6/reshade-addons/assets/154111356/2f532f24-d0a4-47b6-934c-4da025ee85f9)

**Comment by darthmalak1986** [comment]
but now if i move X scale over depth input

i have like ghosting

I dont know what in the hell is going, in 1.5 1.5 is fine 

Wtf?

Can someone help me out?
![Captura de pantalla (1041)](https://github.com/cot6/reshade-addons/assets/154111356/b449332c-c421-47b1-b446-dea90294eccc)

**Comment by cot6** [comment]
From the screenshot, I think you have to set the depth input offset.
Note that the offset is by pixels. Offset X/Y and Scale X/Y are affected by each other, so repeat the increase or decrease until the game screen and the depth buffer are matched.

This issue is out of the scope of add-on support, so please continue to ask help on Discord.

**Comment by darthmalak1986** [comment]
![Captura de pantalla (1059)](https://github.com/cot6/reshade-addons/assets/154111356/e182e918-c485-407f-a17f-ebae4570a7c1)

thank you friend, im just new on this, is giving issues when using dlss >S
