### ISSUE TITLE
The possibility of zip bombing oneself 

### ISSUE THREAD

**Issue by elbadcode** [cot6/reshade-addons#4]
hey this is more of a dumb user error than an actual issue, but it seems like an issue that would be easy to prevent with some failsafes. Basically I had set screenshot addon to capture unlimited number of frames and I guess accidentally turned off the overlay and accidentally pressed the capture button before tabbing out of my game to work on something else. Some time later my PC began to lag like crazy and I saw that my C drive had 0 MB free. Thankfully I have enough RAM that I was able to look around for the issue and found that my screenshots folder had reached over 300 GB in only a few minutes and was able to delete them and resolve the issue. But if I was on a single drive with lower RAM I'm sure that my PC would've crashed and likely there would've been some windows corruption. Therefore I'd propose adding an auto shut off when a certain file size is reached per session

**Comment by cot6** [comment]
Opened a new branch for feedback.
If you require a different implementation than what was implemented in the branch, please continue to discuss it here.
If you have any opinions in the scope of the pull requrest, please discuss it in there.

**Comment by elbadcode** [comment]
the change is perfect thanks for the quick fix!
